[cire] Step-2 GET 요청으로 회원가입 기능 구현
codesquad-members-2023/be-java-was pull request #38
Opened 2023-04-05 08:33 UTC by dltpwns0

# 아쉬운 점 1

예외 처리에 대한 부분이 너무 아쉽다.
나중에 시간이 난다면, 따로 구현을 해야할 것 같다.

# 아쉬운 점 2

요청 파라미터를 객체로 변환해주는 ObjectMapper를 따라한 UserMapper를 구현했지만, 너무 이상하게 구현을 했다..

1. 먼저 객체의 생성자 매개변수와, 요청 파라미터의 순서가 맞아야 한다는 문제가 있다. (나의 수준으론 해결이 어려울 것 같다 ㅜㅜ)
2. 리플렉트 API를 사용하면, OOP에 위배될 수 있어 사용하면 좋지 않다고 하는데, 사용했다. 
-> 왜 사용하면 안되는지 모르면서 그냥 사용 (생성자의 매개변수만 참고하는 정도는 될 것같은데 말이다)
3. 예외처리도 제대로 되지 않았다. (나중에..)

# 좋았던 점

그래도 이상하게 구현하긴 했지만, 배운점도 있었다.

스프링의 코드를 보면 가끔씩 `Class<?>` 가 왜 나오는지 몰랐지만, 이번에 알게됬다.

2023-04-06 01:25 UTC, honux77 commented on src/test/java/process/RequestProcessTest.java
> +        byte[] body = requestProcess.makeResponse(head);
head 스트링으로 한번에 body를 받아버리는군요. 
너무 큰일을 하는 것 같은데 조금 쪼개도 좋을 것 같아요.

2023-04-06 01:45 UTC, honux77 commented on src/main/java/model/HttpRequestHead.java
> +    private final Map<String, String> MIMEHeader;
MIME이 여기서 왜 나오는지 모르겠어요.

2023-04-06 01:47 UTC, honux77 commented on src/main/java/model/HttpRequestHead.java
> +    private final Map<String, String> MIMEHeader;
startLine을 제외한 나머지를 :으로 구분해서 key value로 나누려고 한 것 같은데 그것과 MIME은 다릅니다. 적절한 변수명과 메소드명을 생각해서 고쳐야 할 것 같아요. 변수명 때문에 제가 엄청 오랫동안 고민을 했어요 ㅜㅜ

2023-04-06 01:47 UTC, honux77 requested changes
HTTP Request에 대해 공부를 하고 메소드 이름을 바꿔주세요.

2023-04-06 09:15 UTC, dltpwns0 commented on src/main/java/model/HttpRequestHead.java
> +    private final Map<String, String> MIMEHeader;
죄송합니다 ㅜㅜ
표준 HTTP 헤더 형식을 좀 더 공부하겠습니다!!

2023-04-07 00:03 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +        readRequestMIME(br, stringBuilder);
여전히 여기에도 남아 있네요. 이것도 고쳐주세요.

2023-04-07 00:04 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +            String requestHead = readRequestHead(br);
```suggestion
            List<String> requestHead = readRequestHead(br);            
```
\n 으로 구분하는 것보다 이게 좋지 않을까요?

2023-04-07 00:05 UTC, honux77 requested changes
여전히 MIME 이름의 메소드가 남아 있는데 왜 사용했는지 궁금합니다. 오후에 잠시 이야기 해봐요.

2023-04-08 22:43 UTC, honux77 commented on src/test/java/service/UserServiceTest.java
> +}
간만에 EOL ㅎㅎ

2023-04-10 08:25 UTC, honux77 commented on src/main/java/util/MyObjectMapper.java
> +        // TODO : 생성자 매개변수의 이름도 사용할 수 없을까?
뭐든 가능합니다 ^^

2023-04-10 08:26 UTC, honux77 commented on src/main/java/util/MyObjectMapper.java
> +public class MyObjectMapper {
이렇게 시도해 본 것도 좋은 것 같아요.

2023-04-10 08:26 UTC, honux77 approved these changes
시레 고생하셨습니다. 화이팅!

2023-04-10 08:26 UTC, merged