[cire] step-6 머스타치 템플릿 엔진 모방하여 구현 및 세션, 로깅 인터셉터 구현
codesquad-members-2023/be-java-was pull request #96
Opened 2023-04-19 15:09 UTC by dltpwns0

# 느낀점

하나의 기능을 구현을하고, 하나의 커밋을 해야한다는 사실을 뼈저리게 느꼈습니다.

하나의 기능을 구현하다가, 또 다른 것도 구현하고 싶어서 하다가, 또 다른 기능을 동시에 구현하다가 커밋하는 타이밍을 놓쳐버렸습니다.
그러다가 버그가 발생했고, 깃의 히스토리 기능도 쓰지 못해서 정신이 나가는 줄 알았습니다.

결과적으로는 한줄한줄 디버깅을 했고, 버그는 찾아서 해결했습니다.
앞으로는 정말 커밋을 잘해야 한다는 것을 느낄 수 있는 미션이었습니다...

# 아쉬운 점

머스타치 템플릿 엔진의 기능을 모방하여 서버 사이드 렌더링 기능을 구현했습니다.

하지만, 현재 코드는 거의 암호화된 수준입니다.

시간 남을때, 리펙토링 하려 합니다. (하지만, 이제 수정할 일 없을 것 같은데 리펙토링을 해야할까요?)

# View 클래스를 아쉽게 구현했다.

스프링의 핸들러 반환 값이 문자열 타입의 ViewName 일 때, 자동으로 파일을 찾아가 렌더링을 합니다.

하지만 현제 저의 코드는, 확장자 명까지 포함된 파일 이름을 viewName으로 반환해야 합니다.

나중에 리펙토링 하려 합니다.

# 아쉽지만 안할 것 같은 것

현재 머스타치 문법을 적용한 HTML 은 index.html, user/list.html 두 개 뿐 입니다.

다른 HTML 도 동적으로 만들면 좋을 것 같지만... 나중에 하려 합니다!

2023-04-20 23:34 UTC, honux77 commented on src/main/java/configure/AppConfiguration.java
> +public class AppConfiguration {
알고 있겠지만 사실 모든 빈이 항상 싱글톤으로 동작하는 건 아닙니다.  https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-factory-scopes 참고해 보세요.

2023-04-20 23:46 UTC, honux77 commented on src/main/java/interceptor/DefaultInterceptor.java
> +        return true;
기본 인터셉터의 실행범위는 잘 모르겠지만 모델엔뷰를 여기서 추가하는 게 살짝 어색하게 느껴집니다.

2023-04-20 23:55 UTC, honux77 reviewed
안녕하세요? 시레 늦어서 죄송합니다 ㅜㅜ. 컨디션이 저조해서...
코멘트처럼 커밋을 자주 하는 습관은 엄청 중요하니 다음에는 지키시고, 그리고 브랜치도 잘 활용하면 좋습니다. 지금처럼 branchV6Copy 와 같은 이상한 이름은 지양해 주세요. 

계속 다양한 고민을 하고 시도해서 참 좋은 것 같네요. 
필수는 아니지만 7단계 정도는 마무리 지으면 좋을 것 같아요.

2023-04-21 00:00 UTC, honux77 commented on build.gradle
> +sourceCompatibility = 15
엇? JDK를 15로 바꿨는데 이유가 있을까요? 특별한 이유가 없다면 11을 사용해 주세요.

2023-04-21 08:45 UTC, honux77 commented on src/main/java/util/MyHandlerMethod.java
> +public class MyHandlerMethod {
클래스 이름이 너무 어색해요. 핸들러와 메소드가 있어서 이렇게 이름을 지은 거 같은데 더 좋은 이름이 없을까요?  ControllerAndMethod 어때요? ㅋㅋ 
그리고 결국은 URL -> method로의 최종 매핑이 필요해서 클래스와 method를 가져오는데, 람다를 사용하면 더 깔끔하게 처리할 수 있지 않을까 생각이 듭니다.

2023-04-21 08:53 UTC, honux77 reviewed
참 그리고 RequestMapping에서     
`public static Method requestHandlerMapping(Class<? extends Controller> controller, ...`
가 조금 더 명확하지 않을까요?

2023-04-21 08:57 UTC, honux77 commented on src/main/java/servlet/DispatcherServlet.java
> +        MyHandlerMethod handlerMethod = new MyHandlerMethod(httpRequest, controllers);
수업 때 말한 것처럼 콘트롤러가 default 인 경우 modelAndView를 만들지 않고 바로 처리하도록 하는 게 좋을 것 같아요.

2023-04-21 08:59 UTC, honux77 commented on src/main/java/interceptor/Interceptor.java
> +    public boolean preHandle(HttpRequest httpRequest, HttpResponse httpResponse, ModelAndView modelAndView);
인터셉터도 마찬가지로 static URL 요청에는 실행하지 않도록 하는 로직의 추가가 필요해 보입니다.

2023-04-21 09:01 UTC, honux77 reviewed
참 전에도 언급한 거 같은데 세션매니저가 Cookie 를 가지는 건 맞지 않아요.
Cookie는 단순히 HttpRequest에 있는 특정 필드일 뿐이고
서버에서는 세션을 유지해야 합니다. 이 부분은 꼭 수정해 주세요. (언제?)

2023-04-21 09:03 UTC, honux77 requested changes
시레~ 요구사항 구현하느라 수고 많으셨어요. 늦은 리뷰 죄송하고 몇가지 그래도 중요한 피드백을 남겼으니 반영해 주면 좋을 것 같습니다.

2023-04-23 12:37 UTC, dltpwns0 commented
> 시레~ 요구사항 구현하느라 수고 많으셨어요. 늦은 리뷰 죄송하고 몇가지 그래도 중요한 피드백을 남겼으니 반영해 주면 좋을 것 같습니다.

넵 알겠습니다!

2023-04-24 07:58 UTC, cire0304 commented
> 참 전에도 언급한 거 같은데 세션매니저가 Cookie 를 가지는 건 맞지 않아요. Cookie는 단순히 HttpRequest에 있는 특정 필드일 뿐이고 서버에서는 세션을 유지해야 합니다. 이 부분은 꼭 수정해 주세요. (언제?)

호눅스! 질문이 있습니다.
저는 현재 코드에서 세션매니저가 1) 클라이언트 객체에서 쿠키 객체를 가져오고, 2) 쿠키 객체에서 쿠키 값을 읽어 섹션을 가져오는 것으로 이했습니다.

제가 궁금한 점은 섹션매니저의 필드에 쿠키 객체는 없지만, 메소드 실행 중 쿠키 객체를 사용하게 되는 것도, 세션매니저가 Cookie를 가지고 있게 되는 것인지 궁금합니다!

2023-04-24 13:29 UTC, honux77 commented
시레~ 섹션 (X) 세션 (O) 글 쓰고 나면 한 번 더 맞게 썼는지 검토하는 습관을 가지면 좋을 거 같아요. 
코드를 다시 읽어보니 제가 잘못 이해했네요. 세션 코드에는 아무 문제가 없네요 ㅜㅜ. 죄송합니다.

2023-04-24 13:29 UTC, merged

2023-04-24 13:43 UTC, dltpwns0 commented
> 시레~ 섹션 (X) 세션 (O) 글 쓰고 나면 한 번 더 맞게 썼는지 검토하는 습관을 가지면 좋을 거 같아요. 코드를 다시 읽어보니 제가 잘못 이해했네요. 세션 코드에는 아무 문제가 없네요 ㅜㅜ. 죄송합니다.

아닙니다 호눅스!
오히려 항상 제 읽기 어려운 코드(분발하겠습니다 ㅜㅜ)를  리뷰해주셔서 감사합니다.

그리고 글을 쓰고 검토하는 습관을 가지도록 하겠습니다!!